In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [3]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [4]:
sentences=[
    'i love my dog',
    'I love mY cat',
    'You love my dog!',
    'Do you think my dog is amazing?'
]

In [5]:
len(sentences[0])

13

In [6]:
tokenizer=Tokenizer(num_words=100, oov_token='OOV')
tokenizer.fit_on_texts(sentences)
word_index=tokenizer.word_index
print(word_index)

{'OOV': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}


In [7]:
sequences=tokenizer.texts_to_sequences(sentences)
print(sequences)

[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]


In [8]:
padded=pad_sequences(sequences)
padded

array([[ 0,  0,  0,  5,  3,  2,  4],
       [ 0,  0,  0,  5,  3,  2,  7],
       [ 0,  0,  0,  6,  3,  2,  4],
       [ 8,  6,  9,  2,  4, 10, 11]])

In [9]:
#test data
sentence=['i really love my amazing dog',
             'my dog loves my mantee'
         ]
sequences=tokenizer.texts_to_sequences(sentence)
sequences #in the o/p 'amazing' is 1 since it is being tokenized as OOV(OUT OF VOCAB) for test data

[[5, 1, 3, 2, 11, 4], [2, 4, 1, 2, 1]]

In [20]:
padded_testdata=pad_sequences(sequences)
padded_testdata

array([[ 5,  1,  3,  2, 11,  4],
       [ 0,  2,  4,  1,  2,  1]])

### Practice with a Dataset

In [21]:
import pandas as pd

In [22]:
df=pd.read_csv('bbc-text.csv')

In [23]:
df.head()

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...

In [32]:
df.iloc[0][1]

'tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room  the way people watch tv will be radically different in five years  time.  that is according to an expert panel which gathered at the annual consumer electronics show in las vegas to discuss how these new technologies will impact one of our favourite pastimes. with the us leading the trend  programmes and other content will be delivered to viewers via home networks  through cable  satellite  telecoms companies  and broadband service providers to front rooms and portable devices.  one of the most talked-about technologies of ces has been digital and personal video recorders (dvr and pvr). these set-top boxes  like the us s tivo and the uk s sky+ system  allow people to record  store  play  pause and forward wind tv programmes when they want.  essentially  the technology allows for much more personalised tv. they are also being built-in to high

In [1]:
stopwords =  [ "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but", "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from", "further", "had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its", "itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so", "some", "such", "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too", "under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're", "we've", "were", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "would", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves" ]

In [2]:
len(stopwords)

153

In [29]:
a=df.shape

In [30]:
length=a[0]
length

2225

In [33]:
sentences=[]
for i in range(length):
    sentences.append(df.iloc[i][1])

In [45]:
labels=[]
for i in range(length):
    labels.append(df.iloc[i][0])

In [34]:
len(sentences)

2225

In [35]:
sentences[0]

'tv future in the hands of viewers with home theatre systems  plasma high-definition tvs  and digital video recorders moving into the living room  the way people watch tv will be radically different in five years  time.  that is according to an expert panel which gathered at the annual consumer electronics show in las vegas to discuss how these new technologies will impact one of our favourite pastimes. with the us leading the trend  programmes and other content will be delivered to viewers via home networks  through cable  satellite  telecoms companies  and broadband service providers to front rooms and portable devices.  one of the most talked-about technologies of ces has been digital and personal video recorders (dvr and pvr). these set-top boxes  like the us s tivo and the uk s sky+ system  allow people to record  store  play  pause and forward wind tv programmes when they want.  essentially  the technology allows for much more personalised tv. they are also being built-in to high

In [37]:
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(len(word_index))

29727


In [38]:
sequences=tokenizer.texts_to_sequences(sentences)

In [42]:
padded=pad_sequences(sequences,padding='post')

In [43]:
padded[0]

array([177, 265,   7, ...,   0,   0,   0])

In [44]:
padded.shape

(2225, 4491)

In [46]:
len(labels)

2225

In [54]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(labels)
label_word_index = tokenizer.word_index
print(len(label_word_index))

5


In [55]:
label_word_index

{'sport': 1, 'business': 2, 'politics': 3, 'tech': 4, 'entertainment': 5}

In [56]:
label_sequences=tokenizer.texts_to_sequences(labels)

In [57]:
print(label_sequences)

[[4], [2], [1], [1], [5], [3], [3], [1], [1], [5], [5], [2], [2], [3], [1], [2], [3], [1], [2], [4], [4], [4], [1], [1], [4], [1], [5], [4], [3], [5], [3], [4], [5], [5], [2], [3], [4], [5], [3], [2], [3], [1], [2], [1], [4], [5], [3], [3], [3], [2], [1], [3], [2], [2], [1], [3], [2], [1], [1], [2], [2], [1], [2], [1], [2], [4], [2], [5], [4], [2], [3], [2], [3], [1], [2], [4], [2], [1], [1], [2], [2], [1], [3], [2], [5], [3], [3], [2], [5], [2], [1], [1], [3], [1], [3], [1], [2], [1], [2], [5], [5], [1], [2], [3], [3], [4], [1], [5], [1], [4], [2], [5], [1], [5], [1], [5], [5], [3], [1], [1], [5], [3], [2], [4], [2], [2], [4], [1], [3], [1], [4], [5], [1], [2], [2], [4], [5], [4], [1], [2], [2], [2], [4], [1], [4], [2], [1], [5], [1], [4], [1], [4], [3], [2], [4], [5], [1], [2], [3], [2], [5], [3], [3], [5], [3], [2], [5], [3], [3], [5], [3], [1], [2], [3], [3], [2], [5], [1], [2], [2], [1], [4], [1], [4], [4], [1], [2], [1], [3], [5], [3], [2], [3], [2], [4], [3], [5], [3], [4], [2],

### Sentiment of IMDB Movies Dataset

In [1]:
import tensorflow_datasets as tfds

In [2]:
imdb,info= tfds.load("imdb_reviews", with_info=True, as_supervised=True)

In [3]:
import numpy as np

In [4]:
train_data, test_data = imdb['train'], imdb['test']

In [5]:
training_sentences=[]
training_labels=[]

testing_sentences=[]
testing_labels=[]

In [6]:
for s,l in train_data:
    training_sentences.append(str(s.numpy()))
    training_labels.append(l.numpy())

In [7]:
for s,l in test_data:
    testing_sentences.append(str(s.numpy()))
    testing_labels.append(l.numpy())

In [8]:
len(training_sentences)

25000

In [9]:
len(training_labels)

25000

In [10]:
len(testing_sentences)

25000

In [11]:
len(testing_labels)

25000

In [12]:
import tensorflow as tf

In [13]:
training_labels_final = np.array(training_labels)

In [14]:
testing_labels_final=np.array(testing_labels)

In [15]:
vocab_size=10000
embedding_dim=16
max_length=120
trunc_type='post'

In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [17]:
tokenizer=Tokenizer(num_words=vocab_size, oov_token='OOV')
tokenizer.fit_on_texts(training_sentences)
word_index=tokenizer.word_index

sequences=tokenizer.texts_to_sequences(training_sentences)
padded=pad_sequences(sequences, maxlen=max_length, truncating= trunc_type)

In [18]:
testing_sequences=tokenizer.texts_to_sequences(testing_sentences)
testing_padded=pad_sequences(testing_sequences, maxlen=max_length, truncating= trunc_type)

In [19]:
print("training sequences",len(sequences))
print("training padded",len(padded))
print("Testing sequences", len(testing_sequences))
print("testing padded",len(testing_padded))

training sequences 25000
training padded 25000
Testing sequences 25000
testing padded 25000


In [20]:
len(sequences[1])

149

In [29]:
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

def decode_review(text):
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

print(decode_review(padded[1]))
print(training_sentences[1])

b perhaps because i was so young innocent and OOV when i saw it this movie was the cause of many OOV nights for me i haven't seen it since i was in seventh grade at a OOV school so i am not sure what effect it would have on me now however i will say that it left an impression on me and most of my friends it did serve its purpose at least until we were old enough and OOV enough to analyze and create our own opinions i was particularly terrified of what the newly converted post rapture christians had to endure when not receiving the mark of the beast i don't want to spoil the movie
b"Perhaps because I was so young, innocent and BRAINWASHED when I saw it, this movie was the cause of many sleepless nights for me. I haven't seen it since I was in seventh grade at a Presbyterian school, so I am not sure what effect it would have on me now. However, I will say that it left an impression on me... and most of my friends. It did serve its purpose, at least until we were old enough and knowledgea

In [21]:
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length = max_length),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [22]:
len(training_sentences[0])

601

In [23]:
len(sequences[0])

108

In [24]:
len(testing_sequences[0])

167

In [25]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 120, 16)           160000    
_________________________________________________________________
flatten (Flatten)            (None, 1920)              0         
_________________________________________________________________
dense (Dense)                (None, 6)                 11526     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 7         
Total params: 171,533
Trainable params: 171,533
Non-trainable params: 0
_________________________________________________________________


In [26]:
num_epochs = 10
model.fit(padded, training_labels_final, epochs=num_epochs, validation_data=(testing_padded, testing_labels_final))

Train on 25000 samples, validate on 25000 samples
Epoch 1/10
25000/25000 [==============================] - ETA: 11:57 - loss: 0.6914 - accuracy: 0.531 - ETA: 49s - loss: 0.6903 - accuracy: 0.5583  - ETA: 30s - loss: 0.6926 - accuracy: 0.524 - ETA: 21s - loss: 0.6914 - accuracy: 0.529 - ETA: 15s - loss: 0.6919 - accuracy: 0.518 - ETA: 11s - loss: 0.6914 - accuracy: 0.512 - ETA: 9s - loss: 0.6922 - accuracy: 0.518 - ETA: 8s - loss: 0.6919 - accuracy: 0.52 - ETA: 7s - loss: 0.6914 - accuracy: 0.52 - ETA: 6s - loss: 0.6901 - accuracy: 0.54 - ETA: 5s - loss: 0.6884 - accuracy: 0.55 - ETA: 5s - loss: 0.6866 - accuracy: 0.55 - ETA: 4s - loss: 0.6840 - accuracy: 0.56 - ETA: 4s - loss: 0.6782 - accuracy: 0.58 - ETA: 3s - loss: 0.6712 - accuracy: 0.59 - ETA: 3s - loss: 0.6657 - accuracy: 0.60 - ETA: 3s - loss: 0.6548 - accuracy: 0.61 - ETA: 2s - loss: 0.6421 - accuracy: 0.62 - ETA: 2s - loss: 0.6346 - accuracy: 0.63 - ETA: 2s - loss: 0.6255 - accuracy: 0.64 - ETA: 2s - loss: 0.6140 - accuracy: 

25000/25000 [==============================] - ETA: 7s - loss: 3.5326e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.6265e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.4075e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.3200e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.1850e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.1483e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.1240e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.1307e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.0988e-04 - accuracy: 1.00 - ETA: 2s - loss: 3.0481e-04 - accuracy: 1.00 - ETA: 1s - loss: 3.0153e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9935e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9963e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9885e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9823e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9741e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9890e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9744e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9546e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9687e-04 - accuracy: 1.00 - ETA: 1s - loss: 2.9876e-04 - accu

In [27]:
e = model.layers[0]
weights = e.get_weights()[0]
print(weights.shape) # shape: (vocab_size, embedding_dim)

(10000, 16)


In [31]:
import io

out_v = io.open('vecs.tsv', 'w', encoding='utf-8')
out_m = io.open('meta.tsv', 'w', encoding='utf-8')
for word_num in range(1, vocab_size):
    word = reverse_word_index[word_num]
    embeddings = weights[word_num]
    out_m.write(word + "\n")
    out_v.write('\t'.join([str(x) for x in embeddings]) + "\n")
out_v.close()
out_m.close()